# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5bc51be087dee8ab560005ff9ecd5f2046b87f2305cb4e6ca60cdedd9bc37b139dc8afd4e2da3b7b6b80704938c897b1a95f150c14a030fba6d5e4b942939d7f

test:
  secret_key_base: 60f94a804da770d5abea79a461ed34362b77deeffeb1c1036adf125cd73cdb86ff72a75abedb2e75a53e90c215c1cf8e188611129d240af187248a139e36fd90

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
